AWSTemplateFormatVersion: '2010-09-09'
Description: 'This solution consists of a lambda functions which is used to fetch
  logs from MongoDB Atlas and ingest to Sumo Logic.

  '
Metadata:
  AWS::ServerlessRepo::Application:
    Author: Sumo Logic
    Description: This solution consists of a lambda functions which is used to fetch
      logs from MongoDB Atlas and ingest to Sumo Logic.
    HomePageUrl: https://github.com/SumoLogic/sumologic-mongodb-atlas
    Labels:
    - lambda
    - sumologic
    - atlas
    - serverless
    - MongoDBAtlas
    LicenseUrl: ./LICENSE
    Name: sumologic-mongodb-atlas
    ReadmeUrl: ./README.md
    SemanticVersion: 1.0.17
    SourceCodeUrl: https://github.com/SumoLogic/sumologic-mongodb-atlas
    SpdxLicenseId: Apache-2.0
Outputs:
  MongoDBAtlasFunction:
    Description: MongoDBAtlasScheduler Function ARN
    Value:
      Fn::GetAtt:
      - MongoDBAtlasFunction
      - Arn
	MongoDBAtlasTable:
			Description: MongoDBAtlasTable DynamoDB Table Name
			Value: !Ref MongoDBAtlasTable
Parameters:
  HttpLogsEndpoint:
    Type: String
  HttpMetricsEndpoint:
    Type: String
  OrganizationId:
    Type: String
  PrivateApiKey:
    Type: String
  ProjectId:
    Type: String
  PublicApiKey:
    Type: String
Resources:
  MongoDBAtlasFunction:
    Properties:
      CodeUri: ./target/aws/build/
      Environment:
        Variables:
          ENABLE_CONSOLE_LOG: 'false'
          ENVIRONMENT: aws
          HTTP_LOGS_ENDPOINT:
            Ref: HttpLogsEndpoint
          HTTP_METRICS_ENDPOINT:
            Ref: HttpMetricsEndpoint
          ORGANIZATION_ID:
            Ref: OrganizationId
          PRIVATE_API_KEY:
            Ref: PrivateApiKey
          PROJECT_ID:
            Ref: ProjectId
          PUBLIC_API_KEY:
            Ref: PublicApiKey
      Events:
        ScheduleRule:
          Properties:
            Schedule: rate(10 minutes)
          Type: Schedule
      Handler: main.main
      MemorySize: 256
			Policies:
			- Version: "2012-10-17"
				Statement:
				- Effect: Allow
					Action:
					- dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:GetItem
          - dynamodb:Scan
          - dynamodb:Query
          Resource: !GetAtt MongoDBAtlasTableResource.Arn
      Runtime: python3.11
      Timeout: 900
    Type: AWS::Serverless::Function

	MongoDBAtlasTableResource:
		Type: AWS::DynamoDB::Table
		Properties:
			TableName: !Sub ${AWS::StackName}-mongodbatlastable
			AttributeDefinitions:
			- AttributeName: id
				AttributeType: S
			KeySchema:
			- AttributeName: id
				KeyType: HASH
			ProvisionedThroughput:
				ReadCapacityUnits: 5
				WriteCapacityUnits: 5
Transform: AWS::Serverless-2016-10-31
