AWSTemplateFormatVersion: '2010-09-09'
Description: 'This solution consists of a lambda functions which is used to fetch
  logs from ${APPNAME} and ingest to Sumo Logic.

  '
Outputs:
  ${APPNAME_SINGLE}Function:
    Description: ${APPNAME_SINGLE}Scheduler Function ARN
    Value:
      Fn::GetAtt:
      - ${APPNAME_SINGLE}Function
      - Arn
Parameters:

Resources:

  ${APPNAME_SINGLE}Function:
    Properties:
      CodeUri: s3://appdevstore/${APPNAME_SINGLE}.zip
      Environment:
        Variables:
          ENVIRONMENT: "aws"
      Events:
        ScheduleRule:
          Properties:
            Schedule: rate(5 minutes)
          Type: Schedule
      Handler: main.main
      MemorySize: 256
      Policies:
          - AmazonDynamoDBFullAccess
      Runtime: python3.7
      Timeout: 300
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
