name: "Run Static tests"
on: [workflow_dispatch, pull_request]

jobs:
  run-test:
    name: "Run Security & Linting Tests"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dev dependencies
        run: python -m pip install -U pip flake8 bandit mypy

      - name: Run Security Tests
        run: |
          bandit -r sumomongodbatlascollector/ --skip B108,B113,B314,B405,B404,B501,B506,B602,B604,B605,B607,B608

      - name: Run Linting Tests
        run: |
          flake8 --max-line-length=120 --ignore=E231,E225,F541,E501,E402,F841,W605,E731,E722,C901,F821  sumomongodbatlascollector/

      - name: Static Type Checks
        continue-on-error: true
        run: |
          cd sumomongodbatlascollector/
          mypy --install-types ./main.py
          mypy ./main.py --disable-error-code=import-untyped
          mypy --install-types ./api.py
          mypy ./api.py --disable-error-code=import-untyped

  build-test:
    name: "Run Build and Install Tests"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install build dependencies
        run: |
          python -m pip install -U pip wheel setuptools
      - name: "Build"
        run: |
          python main.py sdist bdist_wheel

      - name: "Install"
        run: |
          pip install dist/sumologic_appdevutils*.whl

      - name: "Test CLITool version command"
        run: |
          sumoappsuite version
